
export const UPDATE_CURRENT_DAY = 'UPDATE_CURRENT_DAY'
export const UPDATE_CURRENT_WEEK = 'UPDATE_CURRENT_WEEK'
export const UPDATE_CURRENT_MONTH = 'UPDATE_CURRENT_MONTH'
export const GO_TO_PLAN_VIEW = 'GO_TO_PLAN_VIEW'
export const CREATE_ASSIGNMENT_PLAN = 'CREATE_ASSIGNMENT_PLAN'

